version: '3.5'

# DB_HOSTNAME and APP_DIR must be defined in
# .env (in same dir as this file)

services:
  # transcendence container
  nest_app:
    container_name: nest_app
    hostname: nest_app
    build:
      context: .
      args:
        - DB_HOST=${DB_HOST}
        - APP_DIR=${APP_DIR}
        - PUBLIC_IP=${PUBLIC_IP}
    depends_on:
      - db
    ports:
      - 8000:8000
      - 3000:3000
    # adding .env file (same dir as this file)
    volumes:
      - .env:${APP_DIR}/backend/.env

  # database container
  db:
    container_name: db
    hostname: ${DB_HOST}
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # forward port 5432 if you want to connect to database
