version: '3.5'
services:
  nest_app:
    container_name: nest_app
    build: .
    depends_on:
      - db
    ports: 
      - 3000:3000
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./.env:/usr/src/app/backend/.env

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
