version: '3.5'
services:
  app:
    container_name: app
    image: rcammaro/transcendence:127.0.0.1
    depends_on:
      - db
    ports: 
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
    external: false