version: '3.5'
services:
  nest_app:
    container_name: nest_app
    hostname: nest_app
    build:
      context: .
      args:
        - DB_HOSTNAME=${DB_HOSTNAME}
        - APP_DIR=${APP_DIR}
    depends_on:
      - db
    ports: 
      - 3000:3000
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./.env:${APP_DIR}/backend/.env

  db:
    container_name: db
    hostname: ${DB_HOSTNAME}
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
