version: '3.5'
services:
  db:
    container_name: db_david
    image: postgres
    ports: 
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: hola
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080


# how to access the database client:
# docker exec -it db psql -U postgres